apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-cluster-1
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      cluster: my-redis-cluster-1
  template:
    metadata:
      labels:
        app: redis
        cluster: my-redis-cluster-1
    spec:
      containers:
      - name: redis
        image: redis:6.2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-my-redis-cluster-1