apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-my-redis-cluster-1
  namespace: redis
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pv-redis-server