---
# Source: openfga/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfga-job-status-reader
  namespace: openfga
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
---
# Source: openfga/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfga-job-status-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfga-job-status-reader
subjects:
- kind: ServiceAccount
  name: openfga
