---
# Source: openfga/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfga
  labels:
    helm.sh/chart: openfga-0.2.13
    app.kubernetes.io/name: openfga
    app.kubernetes.io/instance: openfga
    app.kubernetes.io/version: "v1.6.0"
    app.kubernetes.io/managed-by: Helm
