name: Issue Check Inactive

on:
  schedule:
    - cron: "0 19 * * *"

env: 
  TZ: Asia/Makassar

permissions:
  contents: read

jobs:
  issue-check-inactive:
    permissions:
      issues: write 
     
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-inactive'
          inactive-label: 'inactive'
          inactive-day: 7
          issue-state: open
          exclude-labels: 'bug,planned,$exclude-empty'